services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app/backend
      - ./frontend/dist:/usr/src/frontend/dist
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:
